# Generated by Django 4.0.1 on 2022-03-30 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_address_phone_alter_hotel_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='api.address'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='api.phone'),
        ),
    ]
