# Generated by Django 4.0.1 on 2022-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
    ]
