# Generated by Django 4.0.1 on 2022-04-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('in_cleaning', 'Em Limpeza'), ('in_maintenance', 'Em Manutenção')], default='available', max_length=40),
        ),
    ]
